apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-sre-app
  namespace: react-sre-app
spec:
  template:
    spec:
      containers:
      - name: react-sre-app
        resources:
          limits:
            cpu: "300m"
            memory: "300Mi"
          requests:
            cpu: "100m"
            memory: "150Mi"
