# Secret: Store sensitive configuration data
# Purpose: Securely store credentials, tokens, keys, etc.
#
# Secrets are like ConfigMaps but for sensitive data. They're encoded (not encrypted)
# by default, but Kubernetes prevents them from being casually viewed.
# In production, you'd want to use a proper secret management system like Vault.
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: k8s-demo
type: Opaque
data:
  # Values must be base64 encoded
  # echo -n "dev-secret-key-12345" | base64
  SECRET_KEY: ZGV2LXNlY3JldC1rZXktMTIzNDU=
  # echo -n "password123" | base64
  DB_PASSWORD: cGFzc3dvcmQxMjM=
