apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: sre-monitoring
  labels:
    app: prometheus
spec:
  ports:
  - port: 9090
    targetPort: 9090
    name: web
  selector:
    app: prometheus
  type: ClusterIP
